### PR TITLE
Use instance profile

### LINKED ISSUE #7: Support IAM roles on EC2 instances
When deploying GoCD to AWS it is best practice to use an IAM instance profile on the EC2 instance to provide AWS API access. It would be good if this plugin supported this method, possibly defaulting to an IAM profile if the key and secret are not specified.

### PR DESCRIPTION
**Pull request by aarnone**
Make optional API Access Key and Secret Access Key.
When they are left blank, the IAM role from the instance profile it is used.

Fixes #7

### CODE REVIEW

**Comment by Diogomrol** [comment]
Sorry for not replying sooner, I will take a look at it tomorrow

**Comment by Diogomrol** [comment]
@aarnone Just a small question: what happens if the user fills AWS Access Key field, for example, and leaves the Secret Key one empty?

Tomorrow I will make some manual checks on this and merge it if all goes well.

**Comment by tomzo** [comment]
> Tomorrow I will make some manual checks on this and merge it if all goes well.

In my fork I have added quite a lot of test coverage. Mostly at unit level, but also with actual AWS services.

@Diogomrol would you mind merging this only after adding tests? There are barely any in the master and in this PR.

> what happens if the user fills AWS Access Key field, for example, and leaves the Secret Key one empty?

That would be a great case for 2-3 unit tests.

**Comment by Diogomrol** [comment]
@aarnone care to add some tests for this and validate the scenario of only filling one of the fields?

I think that if the user fills the AWS Access Key field then the others should also be mandatory, in order to avoid weird runtime behaviors and user experience.

**Comment by aarnone** [comment]
Hi @Diogomrol,@tomzo

Thanks for the review!

> @aarnone Just a small question: what happens if the user fills AWS Access Key field, for example, and leaves the Secret Key one empty?

It uses the credentials only if both Access Key and Secret Key are non-empty. See [here](https://github.com/Diogomrol/gocd-s3-artifact-plugin/pull/8/files#diff-d6ff7d8bb6553c9e73d4e0012a0d7e9aR29).

> @aarnone care to add some tests for this and validate the scenario of only filling one of the fields?
> 
> I think that if the user fills the AWS Access Key field then the others should also be mandatory, in order to avoid weird runtime behaviors and user experience.

yep, I'll do that. Not sure exactly when, though.

**Comment by Diogomrol** [comment]
@aarnone my biggest concern is that the suggested implementation might lead to a strange user experience.

As a user, if I fill AWS Access Key field, then the Secret Key one should be mandatory, otherwise I will save my configuration without a Secret Key and what happens next is kinda not obvious.

Does this make sense?

**Comment by aarnone** [comment]
> @aarnone my biggest concern is that the suggested implementation might lead to a strange user experience.
> 
> As a user, if I fill AWS Access Key field, then the Secret Key one should be mandatory, otherwise I will save my configuration without a Secret Key and what happens next is kinda not obvious.
> 
> Does this make sense?

@Diogomrol  Yeah, I know what you mean, and I agree it's unclear/misleading.
I'll add an extra validation, in case only one of the two fields is filled. Sounds right?

**Comment by Diogomrol** [comment]
> @Diogomrol Yeah, I know what you mean, and I agree it's unclear/misleading.
> I'll add an extra validation, in case only one of the two fields is filled. Sounds right?

Seems cool :)

**Pull request merged**
